-- DROP TABLE IF EXISTS SCHEDULE CASCADE;
-- DROP TABLE IF EXISTS COURSESLOT CASCADE;
-- DROP TABLE IF EXISTS COURSE_TERM CASCADE;
-- DROP TABLE IF EXISTS COURSE CASCADE;
-- DROP TABLE IF EXISTS PROFESSOR CASCADE;
-- DROP TABLE IF EXISTS USER_PROFILE CASCADE;
-- DROP TABLE IF EXISTS TERM CASCADE;
-- DROP TABLE IF EXISTS PROGRAM CASCADE;
-- DROP TABLE IF EXISTS USER_CREDENTIALS CASCADE;
-- DROP TABLE IF EXISTS PASSWORD_RESET_TOKEN CASCADE;
-- DROP TABLE IF EXISTS REFRESH_TOKENS CASCADE;

-- Create USER_CREDENTIALS table
CREATE TABLE IF NOT EXISTS USER_CREDENTIALS (
    UserID SERIAL PRIMARY KEY,
    UserEmail VARCHAR(255) UNIQUE NOT NULL,
    UserPassword VARCHAR(255) NOT NULL,
    UserAccess VARCHAR(50) DEFAULT 'Default' CHECK (UserAccess IN ('Admin', 'Default')),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- Create PROGRAM table
CREATE TABLE IF NOT EXISTS PROGRAM (
    ProgramID VARCHAR(10) PRIMARY KEY,
    ProgramName VARCHAR(255) NOT NULL,
    TotalYears INT NOT NULL CHECK (TotalYears BETWEEN 1 AND 6),
    SemesterType INT NOT NULL CHECK (SemesterType IN (1, 2, 3)), -- 1 = 1 semester; 2 = 2 semesters; 3 = summer term
    DefaultUnits INT NOT NULL DEFAULT 18 CHECK (DefaultUnits BETWEEN 1 AND 40)
);


-- Create TERM table
CREATE TABLE IF NOT EXISTS TERM (
    TermID VARCHAR(10) PRIMARY KEY,
    ProgramID VARCHAR(10) NOT NULL REFERENCES PROGRAM(ProgramID) ON DELETE CASCADE,
    YearLevel INT NOT NULL CHECK (YearLevel BETWEEN 1 AND 6),
    Semester INT NOT NULL CHECK (Semester BETWEEN 1 AND 3),
    ReqUnits INT,
    UNIQUE(ProgramID, YearLevel, Semester)
);

-- Create USER_PROFILE table
CREATE TABLE IF NOT EXISTS USER_PROFILE (
    UserID INT PRIMARY KEY REFERENCES USER_CREDENTIALS(UserID) ON DELETE CASCADE,
    UserName VARCHAR(255) NOT NULL,
    TermID VARCHAR(10) REFERENCES TERM(TermID) ON DELETE SET NULL
);

-- Create COURSE table
CREATE TABLE IF NOT EXISTS COURSE (
    CourseCode VARCHAR(15) PRIMARY KEY,
    CourseName VARCHAR(255) NOT NULL,
    CourseUnits INT
);

-- Create COURSE_TERM table
CREATE TABLE IF NOT EXISTS COURSE_TERM (
    CourseCode VARCHAR(15) REFERENCES COURSE(CourseCode) ON DELETE CASCADE,
    TermID VARCHAR(10) REFERENCES TERM(TermID) ON DELETE CASCADE,
    PRIMARY KEY (CourseCode, TermID)
);

-- Create PROFESSOR table
CREATE TABLE IF NOT EXISTS PROFESSOR (
    ProfID SERIAL PRIMARY KEY,
    ProfName VARCHAR(255) NOT NULL,
    ProfDepartment VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS COURSESLOT (
    CourseSlotID SERIAL PRIMARY KEY,
    CourseCode VARCHAR(15) NOT NULL REFERENCES COURSE(CourseCode) ON DELETE CASCADE,
    ProfID INT REFERENCES PROFESSOR(ProfID) ON DELETE SET NULL,
    StartTime TIME NOT NULL,
    EndTime TIME NOT NULL,
    ScheduleDay VARCHAR(50),
    RoomCode VARCHAR(20)
);
-- Create SCHEDULE table
CREATE TABLE IF NOT EXISTS SCHEDULE (
    ScheduleID SERIAL PRIMARY KEY,
    UserID INT NOT NULL REFERENCES USER_CREDENTIALS(UserID) ON DELETE CASCADE,
    ScheduleName VARCHAR(255) NOT NULL,
    ScheduleList JSONB DEFAULT '[]'::jsonb,
    TotalUnits INT DEFAULT 0,
    Regular BOOLEAN DEFAULT TRUE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create PASSWORD_RESET_TOKEN table
CREATE TABLE IF NOT EXISTS PASSWORD_RESET_TOKEN (
    ID SERIAL PRIMARY KEY,
    UserEmail VARCHAR(255) NOT NULL REFERENCES USER_CREDENTIALS(UserEmail) ON DELETE CASCADE,
    Token VARCHAR(255) NOT NULL UNIQUE,
    ExpiresAt TIMESTAMP NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create REFRESH_TOKENS table
CREATE TABLE IF NOT EXISTS REFRESH_TOKENS (
    ID SERIAL PRIMARY KEY,
    UserID INT NOT NULL REFERENCES USER_CREDENTIALS(UserID) ON DELETE CASCADE,
    Token VARCHAR(500) NOT NULL UNIQUE,
    ExpiresAt TIMESTAMP NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create USER_PREFERENCES table
CREATE TABLE IF NOT EXISTS USER_PREFERENCES (
    UserID INT PRIMARY KEY REFERENCES USER_CREDENTIALS(UserID) ON DELETE CASCADE,
    BlockedTimes JSONB DEFAULT '[]'::jsonb,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- -------------------------------------------------------------------
-- Indexes (performance + foreign-key join support)
-- -------------------------------------------------------------------
-- FK indexes are not created automatically in Postgres; add them explicitly to avoid slow joins / deletes.
CREATE INDEX IF NOT EXISTS idx_term_programid ON TERM(ProgramID);
CREATE INDEX IF NOT EXISTS idx_user_profile_termid ON USER_PROFILE(TermID);
CREATE INDEX IF NOT EXISTS idx_course_term_termid ON COURSE_TERM(TermID);
CREATE INDEX IF NOT EXISTS idx_courseslot_coursecode ON COURSESLOT(CourseCode);
CREATE INDEX IF NOT EXISTS idx_courseslot_profid ON COURSESLOT(ProfID);
CREATE INDEX IF NOT EXISTS idx_schedule_userid ON SCHEDULE(UserID);
CREATE INDEX IF NOT EXISTS idx_password_reset_token_useremail ON PASSWORD_RESET_TOKEN(UserEmail);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_token ON REFRESH_TOKENS(Token);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_userid ON REFRESH_TOKENS(UserID);